services:
  repo:
    build: .
    container_name: guru-app-test-task
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - .turbo:/app/.turbo
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/guru_db?schema=public"
    command: >
      sh -c "pnpm --filter ./apps/bff... run seed &&
             pnpm turbo run dev"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: guru-app-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guru_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: